### ISSUE TITLE
onChange latency

### ISSUE THREAD

**Issue by ideopunk** [hepter/react-native-modal-selector-searchable#1]
There's some latency with the `onChange` callback. Are there ways to reduce the latency? If this is a known issue, I'm happy to work on it once pointed in the right direction.

**Comment by hepter** [comment]
Can you try the solutions here? https://github.com/peacechen/react-native-modal-selector/issues/140

This issue seems a bit problematic in general. I can't test it because I don't have an iOS device, but I'll take a look at what I can do.

**Comment by ideopunk** [comment]
Using onModalChange does indeed work better :).
